server:
  port: 8888

spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DincaAlex/practica-ms-config-server.git
          search-paths: config-repo
          default-label: main
          clone-on-start: true
          # Autenticaci√≥n (opcional, solo si el repo es privado)
          # username: ${GIT_USERNAME}
          # password: ${GIT_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "*"